// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountActiveSamples(ctx context.Context) (int64, error)
	CountSamples(ctx context.Context) (int64, error)
	CreateSample(ctx context.Context, arg CreateSampleParams) (Sample, error)
	DeleteSample(ctx context.Context, id int64) error
	DeleteSampleByEmail(ctx context.Context, email string) error
	GetAllActiveSamples(ctx context.Context) ([]Sample, error)
	GetAllSamples(ctx context.Context) ([]Sample, error)
	GetSampleByEmail(ctx context.Context, email string) (Sample, error)
	GetSampleByID(ctx context.Context, id int64) (Sample, error)
	GetSamplesPaginated(ctx context.Context, arg GetSamplesPaginatedParams) ([]Sample, error)
	UpdateSample(ctx context.Context, arg UpdateSampleParams) (Sample, error)
}

var _ Querier = (*Queries)(nil)
