app:
  name: go-backend-template
  host: 0.0.0.0
  port: 8097
  timeout: 30s
db:
  migration_path: internal/constant/db/schemas
  migration_path_up: internal/constant/db/schemas/up
  host: localhost
  port: 5432
  user: postgres
  password: secret
  dbname: mobile
  sslmode: disable

logger:
  level: 0